name: API CI Pipeline

on: [ push, workflow_dispatch ]

jobs:
  php-tests:
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
    uses: tastyigniter/workflows/.github/workflows/php-tests.yml@main
    with:
      php-version: ${{ matrix.php }}

  auto-merge-release:
    needs: [ php-tests ]
    uses: tastyigniter/workflows/.github/workflows/auto-merge-release.yml@main
    with:
      release-branch: master
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
